### ISSUE TITLE
can i use this ? 

### ISSUE THREAD

**Issue by ggbbest** [samlaubscher/Stellar-Drift-Game-M2#1]
hello 

can i use this game? my site ? https://c4ei.net 

there is have license like MIT , APACHE . . . ?

thank you for showing source.

**Comment by samlaubscher** [comment]
Hey @ggbbest, thanks for asking!

Yes you can use it, just give me credit where possible :) 

I look forward to seeing it on your site.

**Comment by ggbbest** [comment]
wow thank you very much

if you can download Google play store
ggbwallet download

and c4ei
receive click
and send me address
I will send 10000 c4ei
i will make good thing some day. . .


2021년 12월 23일 (목) 오후 5:06, Sam Laubscher ***@***.***>님이 작성:

**Comment by samlaubscher** [comment]
Thank you, can this be sent to another wallet instead of ggbwallet?

**Comment by ggbbest** [comment]
hello

c4ei.net just registered then appear address show

tell me please

I will send
thank you very much ^^

2022년 1월 4일 (화) 오후 12:04, Sam Laubscher ***@***.***>님이 작성:

**Comment by SupremeSkriptKiddie** [comment]
Sam what's this for?

**Comment by ggbbest** [comment]
address show here ^^


2022년 1월 4일 (화) 오후 12:21, guyfawkes69 ***@***.***>님이 작성:

> Sam what's this for?
>

**Comment by ggbbest** [comment]
Dear Developers,
Perhaps you do not want to receive coins. So I'd like to spend $100, though
it's small. I wonder how you can send it.
It's a very small amount, but would you consider it sincere?

친애하는 개발자분께.
아마도 코인을 받기 싫으신듯 합니다. 그래서 조촐하지만 100$를 보내고 싶습니다. 어떻게 보낼수있는지 궁금합니다.
너무 적은 금액이지만 성의라고 생각해주시겠습니까?

2022년 1월 4일 (화) 오후 12:27, best ggb ***@***.***>님이 작성:

> address show here ^^
>
>
> 2022년 1월 4일 (화) 오후 12:21, guyfawkes69 ***@***.***>님이 작성:
>
>> Sam what's this for?
>>

**Comment by samlaubscher** [comment]
Thank you ggbest, that is very kind! :smile:  I can send you a paypal address? Also, what is the current value of the c4ei coin? I would like to have a bit but I am not sure what the rate is :laughing:

**Comment by ggbbest** [comment]
hello I will  send paypal 100$
if you  PayPal address
send me
thank you ^^


2022년 1월 4일 (화) 오후 10:31, Sam Laubscher ***@***.***>님이 작성:

**Comment by samlaubscher** [comment]
@ggbbest thank you very much! 

My paypal is hakaewt@protonmail.com 

Could you please send it to me in British Pounds £ please :)

I look forward to seeing you use this

**Comment by samlaubscher** [comment]
actually, can you email me via that email. I would like to chat about c4ei with you and the currency

**Comment by samlaubscher** [comment]
Thank you very much for your kind payment and for reaching out to ask to use the source code, I look forward to seeing it in action in the future!

**Comment by ggbbest** [comment]
thank you very much
have a nice day^^

2022년 1월 7일 (금) 오후 8:31, Sam Laubscher ***@***.***>님이 작성:
